apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=./Dockerfile"
    - "--context=git://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@https://github.com/Sanjeevk95/spring-boot-mongo-docker.git" #git://github.com/kunchalavikram1427/connected-app.git#refs/heads/master
    - "--destination=sanjeevk95/springbootmongo:1"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
        - key: .dockerconfigjson
          path: config.json
